name: Demo pipeline

on:
    push:
        branches:
            - dev
    pull_request:
        branches: [main, dev]
    schedule: 
        - cron: "*/1 * * * *"
    
jobs: 
    setup_job:
        runs-on: ubuntu-latest 
        steps:
            - name: create file
              run: touch github-action.txt
            - name: print hello world
              run: echo Hello world
            - name: display readme file
              run: cat README.md

    build_job:
        runs-on: windows-latest
        steps:
            - name: display hello
              run: echo hello

    deploy_job: 
        runs-on: macos-latest
        steps: 
            - run: echo hello from mac

    